### ISSUE TITLE
Footer redirect

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#12]
**Describe the bug**
Incorrect redirect

**Expected behavior**
A click on the button  "  :star:  Give us a star on Github " should redirect to [monsij/StudentPortal](https://github.com/monsij/StudentPortal).

**Screenshots**
![capture](https://user-images.githubusercontent.com/23289387/49494736-9e4db900-f886-11e8-867b-295879639b1d.JPG)

**Comment by monsij** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by gopavasanth** [comment]
I' will work on this, Please assign me :)

**Comment by monsij** [comment]
Assigned @gopavasanth

**Comment by monsij** [comment]
Make a separate PR for this issue @gopavasanth . Also include a description as per the `pull_request_template.md`

**Comment by monsij** [comment]
Solved : #17
