### ISSUE TITLE
Add Python Decouple

### ISSUE THREAD

**Issue by modihere** [monsij/StudentPortal#14]
Add the [python decouple](https://pypi.org/project/python-decouple/) app which separates the settings file from the main Django app for security purposes. 

1. All the important credentials (secret key, debug, email credentials, database credentials) present in settings.py should be defined and initialized in a ".env" file in the main project directory and the settings.py should fetch the data from there. Python decouple does this work very well so use that. 

2. Also take care to make a ".gitignore" file to stop redundant files or files which are specific to people (like migrations, ".env" and the database) from getting uploaded. 

3. The README.md should be updated accordingly for the credentials to be entered first so that the server can be started properly.

These are the basic issues which i found for now and should be patched up soon. You can divide these issues accordingly among different people. 

P.S. Add more steps to readme (like makemigrations, migrate, createsuperuser, dbshell) so that even a beginner can start and explore the app.

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/monsij/StudentPortal/issues/3 (Add Contributors app).

**Comment by monsij** [comment]
@modihere : Do you want to work on it?

**Comment by modihere** [comment]
No no. Let the people learn. I have worked more than enough on Django and i don't have time now. 
Too much for me. :P

**Comment by akashgiricse** [comment]
@monsij , can I work on this issue?

**Comment by monsij** [comment]
Assigned @akashgiricse

**Comment by monsij** [comment]
Solved : #51
