### ISSUE TITLE
Add all packages in a new file

### ISSUE THREAD

**Issue by nguptaa** [monsij/StudentPortal#22]
It becomes a very hectic task to install required packages one by one. Hence creating a file containing all the packages will help users install all packages at once.

Create a new filename requirements.txt and add all the packages used in this project.

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/3 (Add Contributors page), https://github.com/monsij/StudentPortal/issues/14 (Add Python Decouple), and https://github.com/monsij/StudentPortal/issues/5 (Missing app in settings file).
