### ISSUE TITLE
Portal tab title

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#27]
**Describe the bug**
Tab heading wrongly hows "Blog home"

**Expected behavior**
The tab heading should be something like "Student Portal"

**Screenshots**
![tab](https://user-images.githubusercontent.com/23289387/49598055-ced74500-f9a3-11e8-9f74-2a74fde73e24.PNG)

**Comment by nguptaa** [comment]
I want to work on it.

**Comment by monsij** [comment]
Sorry @nguptaa but you are already assigned an issue.

**Comment by monsij** [comment]
Assigned : @Tiyas-13

**Comment by monsij** [comment]
@Tiyas-13 : An update to the task is every page of the portal is showing up "Blog Home" as the title page. So changes are required to made accordingly.

**Comment by Tiyas-13** [comment]
Noted

**Comment by monsij** [comment]
Solved : #45
