### ISSUE TITLE
New tab redirect

### ISSUE THREAD

**Issue by r3trd** [monsij/StudentPortal#29]
Make the profile of contributor to open in new tab in the browser.

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/3 (Add Contributors page), https://github.com/monsij/StudentPortal/issues/25 (Enhancements to contributors page), and https://github.com/monsij/StudentPortal/issues/28 (Portal tab title).

**Comment by Tiyas-13** [comment]
I would like to work on this.

**Comment by monsij** [comment]
Assigned : @Tiyas-13

**Comment by monsij** [comment]
Solved : #34
