### ISSUE TITLE
Add Confirmation Button to Download Tabs

### ISSUE THREAD

**Issue by Tiyas-13** [monsij/StudentPortal#35]
**Is your feature request related to a problem? Please describe.**
The Download tabs like Academic Calender , Holidays, are permanently in view on all pages. Clicking on these tabs downloads the files directly without any confirmation. As a result the files get downloaded multiple times because people have a tendency to click on the links repeatedly.

**Describe the solution you'd like**
Confirmation messages and buttons could be added before the files get downloaded.

**Describe alternatives you've considered**
The links could also redirect to a view of the files on a new tab or via a pop-up, at the end of which it has a download option.

**Additional context**
![screenshot from 2018-12-07 11-46-53](https://user-images.githubusercontent.com/35505246/49630857-e2bb8f00-fa15-11e8-8d2d-a6db6052aa61.png)

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/3 (Add Contributors page), https://github.com/monsij/StudentPortal/issues/29 (New tab redirect), https://github.com/monsij/StudentPortal/issues/27 (Portal tab title), https://github.com/monsij/StudentPortal/issues/28 (Portal tab title), and https://github.com/monsij/StudentPortal/issues/14 (Add Python Decouple).

**Comment by harry-hov** [comment]
I would like to work on this.

**Comment by monsij** [comment]
@harry-hov let your PR get approved xD

**Comment by harry-hov** [comment]
sure @monsij 😄

**Comment by nguptaa** [comment]
I would love to work on this

**Comment by monsij** [comment]
@nguptaa  Would you like to work on this?

**Comment by monsij** [comment]
Assigned : @nguptaa
