### ISSUE TITLE
IP not displayed

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#39]
**Describe the bug**
The recently added feature is not showing time and IP . Weather part is working fine

**Screenshot**
![weather](https://user-images.githubusercontent.com/23289387/49645553-67240700-fa42-11e8-8fe8-fcc995658162.PNG)

**Update**
The IP is showing up on localhost but not on the deployed version. 
![wid2](https://user-images.githubusercontent.com/23289387/49663147-c5b5a900-fa73-11e8-9123-beb869cc5602.PNG)

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/19 (Unusual display size), and https://github.com/monsij/StudentPortal/issues/20 (Current dynamic date,time,weather and user IP).

**Comment by nguptaa** [comment]
I'll have a look

**Comment by monsij** [comment]
Solved: #44
