### ISSUE TITLE
Unequal height 

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#40]
**Describe the bug**
A card for one of the contributors has a greater height than others.

**Screenshot**
![height](https://user-images.githubusercontent.com/23289387/49650298-c63d4800-fa51-11e8-8f32-6282493b8176.PNG)

**Comment by harry-hov** [comment]
im on it

**Comment by monsij** [comment]
Assigned : @harry-hov

**Comment by harry-hov** [comment]
done

**Comment by monsij** [comment]
Solved: #41
