### ISSUE TITLE
Placements/Internships updates

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#43]
Create a framework for uploading updates in the `interviews` app so that new news can be uploaded with Ease. Create a provision for filtering based on company as well

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/monsij/StudentPortal/issues/26 (Screenshots update).

**Comment by gutsytechster** [comment]
Hey @monsij !
Can you help me getting what is needed for this?
I mean do you need a page to upload the news and other things or something else?

**Comment by monsij** [comment]
Yes @gutsytechster . Will contain updates in a posts format each containing label of a company. Each post will contain some information, maybe the students selected or maybe the scheduled interview date and location.

**Comment by gutsytechster** [comment]
Hey can I be assigned to it @monsij!

**Comment by monsij** [comment]
Assigned : @gutsytechster

**Comment by gutsytechster** [comment]
![internship_admin](https://user-images.githubusercontent.com/31796326/49696745-b306b580-fbd4-11e8-8890-03679e74487b.png)

**Comment by gutsytechster** [comment]
Hey @monsij, this is how it looks if we use Django's admin panel to create entries for internships.
Though only admin would be allowed to do that. It means not even a login user to your system can do that. There would be other credentials for entering into django's admin panel created by django command `python manage.py createsuperuser
`

**Comment by monsij** [comment]
Add more fields like dept open to, extra information

**Comment by gutsytechster** [comment]
Yeah! this was just a prototype. I would add more fields as required.

**Comment by gutsytechster** [comment]
![out](https://user-images.githubusercontent.com/31796326/49758549-462f1080-fce5-11e8-93ce-a539fb6c4096.gif)

**Comment by gutsytechster** [comment]
Hey @monsij, how does this layout look to you? For detailed information, the user will click on the `know more about it` link and the page will be redirected to the page containing detailed information. 
I have yet to design that page. Before that I want to make sure if this page looks good to you!

**Comment by monsij** [comment]
Awesome ! . Just change "know more about it" to "More" and squash your commits if you haven't done so.

**Comment by gutsytechster** [comment]
![internship-page](https://user-images.githubusercontent.com/31796326/50056502-19ff0e00-0183-11e9-9855-b97b2fef03c2.png)

**Comment by gutsytechster** [comment]
Hey @monsij, this is how the details will be displayed. Does it look ok?

**Comment by gutsytechster** [comment]
![internship-page2](https://user-images.githubusercontent.com/31796326/50056764-22594800-0187-11e9-8c86-87a61b09e396.png)

**Comment by gutsytechster** [comment]
Or does it look better?
@monsij ^^

**Comment by monsij** [comment]
The [previous one](https://github.com/monsij/StudentPortal/issues/43#issuecomment-447659272) is better

**Comment by monsij** [comment]
Is the one to be displayed after clicking on "More details" ? @gutsytechster

**Comment by gutsytechster** [comment]
![placement-admin](https://user-images.githubusercontent.com/31796326/50057365-5cc6e300-018f-11e9-8dfb-5de0e945ca9a.png)

**Comment by gutsytechster** [comment]
Also are these parameter enough for placments?
I was thinking of adding `job designation`, `qualification needed`, `experience needed`, `last date to apply`.
What do you think about it?

**Comment by monsij** [comment]
Add them.will modify them later

**Comment by monsij** [comment]
Solved : #84
