### ISSUE TITLE
Travis CI configuration

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#46]
The repository doesn't has a continuous integration service. Add one to continuously build the project with every `merge`.

**Comment by nguptaa** [comment]
I would like to work on this.

**Comment by monsij** [comment]
Would you like to leave previously assigned issue?

**Comment by monsij** [comment]
Or work simultaneously

**Comment by nguptaa** [comment]
No. we can be assigned to max two issues right?

**Comment by monsij** [comment]
Great! Be sure to send PRs from different branches for these issues

**Comment by monsij** [comment]
Assigned : @nguptaa

**Comment by monsij** [comment]
Add only a `.travis.yml` file

**Comment by nguptaa** [comment]
@monsij Should choose the pro1 repository right?

**Comment by monsij** [comment]
Hurray! Completed thanks to @nguptaa
