### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#52]
The present `README.md`  looks very limited and brief. A makeover to it is required addressing possibilities ranging from handling virtual environments, frequently encountered bugs to other configuration details.

**Comment by Tiyas-13** [comment]
I would like to work on this.

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/26 (Screenshots update), and https://github.com/monsij/StudentPortal/issues/43 (Placements/Internships updates).

**Comment by monsij** [comment]
Assigned : @Tiyas-13

**Comment by akashgiricse** [comment]
Please add instruction for configuring environment variable using **python-decople** in README.md. 
Add an instruction as following
<br>
----
* Create a file named `.env` in project's root directory (i.e. inside **pro1**, where `.env.example` reside)
and copy the content from `.env.example` file and paste it in `.env` file. 
----
Add the above instruction in **How to use** section just after **Activate your virtual environment**

**Comment by Tiyas-13** [comment]
Noted.

**Comment by monsij** [comment]
Solved : #62
