### ISSUE TITLE
Add all local contacts

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#54]
The contacts list is not yet complete. Add rest of them like restaurants, medical store etc.

P.S : Can be obtained by a local student only.

**Comment by Tiyas-13** [comment]
Would like to do this.

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/3 (Add Contributors page), https://github.com/monsij/StudentPortal/issues/22 (Add all packages in a new file), https://github.com/monsij/StudentPortal/issues/14 (Add Python Decouple), and https://github.com/monsij/StudentPortal/issues/35 (Add Confirmation Button to Download Tabs).
