### ISSUE TITLE
Relocation of sidebar

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#57]
The sidebar presently occupies a lot of place being almost in the middle of the right part of the page. Align it to the bottom with a possible design as shown below:
![sidebar](https://user-images.githubusercontent.com/23289387/49697695-9e301f00-fbe0-11e8-82b5-b994180d7a75.PNG)

**Comment by harry-hov** [comment]
i want to work on this

**Comment by monsij** [comment]
Assigned : @harry-hov

**Comment by monsij** [comment]
Solved : #58
