### ISSUE TITLE
Transport Layer Security(TLS) Error

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#6]
For sending emails to users for registration and password reset, the security layer should be set as `True`. Make this change in `settings.py`

**Comment by gopavasanth** [comment]
I'm working on this, I will submit the patch sooner :-)

**Comment by gopavasanth** [comment]
commit 370261076bcf8ebd3228469b367d8ca7446ba824

**Comment by monsij** [comment]
Solved : #17
