### ISSUE TITLE
Study zone for 1st year

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#63]
The first years aren't able to access their official email ids early in the college. So the study zone for them needs to be made accessible without login.

**Comment by Tiyas-13** [comment]
I would like to work on this

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/monsij/StudentPortal/issues/53 (Improvised study zone).

**Comment by monsij** [comment]
Assigned @Tiyas-13

**Comment by monsij** [comment]
Solved : #91
