### ISSUE TITLE
Add Codecov badge in README.md

### ISSUE THREAD

**Issue by nguptaa** [monsij/StudentPortal#65]
Since Codecov has already been added to the repository, add a Codecov badge to README.md file.

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/52 (README update), https://github.com/monsij/StudentPortal/issues/50 (Codecov coverage configuration), https://github.com/monsij/StudentPortal/issues/3 (Add Contributors page), and https://github.com/monsij/StudentPortal/issues/14 (Add Python Decouple).
