### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by rahulotwani** [monsij/StudentPortal#66]
can be made a bit more user friendly

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/52 (README update), https://github.com/monsij/StudentPortal/issues/26 (Screenshots update), https://github.com/monsij/StudentPortal/issues/65 (Add Codecov badge in README.md), https://github.com/monsij/StudentPortal/issues/43 (Placements/Internships updates), and https://github.com/monsij/StudentPortal/issues/56 (Contributors page update).
