### ISSUE TITLE
Fix About Us section in Footer

### ISSUE THREAD

**Issue by harry-hov** [monsij/StudentPortal#67]
**Describe the bug**
About Us section in Footer needs to be Updated.
There is no break between different sentences. 

**Expected behavior & solution**
There is need of `<br>` in some places.
it should look something like this.
![screenshot 49](https://user-images.githubusercontent.com/37576387/49941459-920dcf80-ff08-11e8-9bd2-03c5749c4168.png)

**Current Screenshots**
Read the last line, don't you think it needs an update?
![screenshot 67 _li](https://user-images.githubusercontent.com/37576387/49942038-2af11a80-ff0a-11e8-86cc-b64e0b84eea3.jpg)

**Optional**
Improve Content of About Us Section.

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/12 (Footer redirect), and https://github.com/monsij/StudentPortal/issues/38 (Find and fix Typos).

**Comment by monsij** [comment]
@Tiyas-13 : Would you like to take up this one?

**Comment by udaymewada** [comment]
I would like to work on this

**Comment by monsij** [comment]
Assigned : @udaymewada

**Comment by monsij** [comment]
Solved : #70
