### ISSUE TITLE
Link Hover

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#68]
**Describe the bug**
Hovering over it makes it grey in colour and hence less visible. Change it appropriately

**Screenshot**
![hover](https://user-images.githubusercontent.com/23289387/49955339-94802180-ff28-11e8-8038-bc9153c2850b.PNG)

**Comment by udaymewada** [comment]
I will work on it

**Comment by monsij** [comment]
@udaymewada Please wind up the issue assigned to you before

**Comment by YashviP** [comment]
i will work on it

**Comment by monsij** [comment]
Assigned : @YashviP
