### ISSUE TITLE
Chanakya portal link change

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#72]
The Chanakya link has migrated to http://14.139.221.18:9001. Make this change in the portal

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/68 (Link Hover), https://github.com/monsij/StudentPortal/issues/28 (Portal tab title), and https://github.com/monsij/StudentPortal/issues/27 (Portal tab title).

**Comment by monsij** [comment]
@chauhannishh You may work on this

**Comment by rahulotwani** [comment]
i can do this

**Comment by monsij** [comment]
Assigned : @rahulotwani
