### ISSUE TITLE
Page title format

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#79]
**Describe the bug**
The pages have title as `StudentPortal:Interviews` . Change it to `Interviews`

**Comment by monsij** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/monsij/StudentPortal/issues/47 (Improved user profile page), https://github.com/monsij/StudentPortal/issues/27 (Portal tab title), https://github.com/monsij/StudentPortal/issues/28 (Portal tab title), https://github.com/monsij/StudentPortal/issues/32 (static profile pages), and https://github.com/monsij/StudentPortal/issues/3 (Add Contributors page).

**Comment by chauhannishh** [comment]
I want to work on this issue.

**Comment by monsij** [comment]
Assigned : @chauhannishh

**Comment by monsij** [comment]
Solved : #80
