### ISSUE TITLE
Webpage not loading in localhost server

### ISSUE THREAD

**Issue by nguptaa** [monsij/StudentPortal#90]
Webpage not loading in localhost server (Server Error 500)

![screenshot 2018-12-20 at 2 27 37 pm](https://user-images.githubusercontent.com/22504975/50273747-9899cb00-0463-11e9-9f81-52151ba6677d.png)

**Comment by monsij** [comment]
Hey @nguptaa for server purposes , debug has been set `False`. set it `True` on your local copy to get it running

**Comment by monsij** [comment]
If it's solved, close the issue @nguptaa
