### ISSUE TITLE
Open/Close Label

### ISSUE THREAD

**Issue by monsij** [monsij/StudentPortal#95]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
From the main interview page, we want a label to show where applying date for the company has crossed or not i.e Open/Closed

**Describe alternatives you've considered**
A label on the front page as shown

**Additional context**
![label](https://user-images.githubusercontent.com/23289387/50350468-46d96980-0565-11e9-92ab-befc540929fe.PNG)

**Comment by gutsytechster** [comment]
Hey @monsij, I 'd like to work on this issue!
Also, I'd like to work on all the remaining UI changes for this.

**Comment by monsij** [comment]
Assigned : @gutsytechster

**Comment by gutsytechster** [comment]
![form-buttons](https://user-images.githubusercontent.com/31796326/50386393-47136980-070b-11e9-8fa3-15382f60758f.png)

**Comment by gutsytechster** [comment]
Hey @monsij, how does these button look?

**Comment by monsij** [comment]
🥇

**Comment by monsij** [comment]
Another , either green or red (open/closed)...so make this form button anything other than red or green

**Comment by gutsytechster** [comment]
![button-dark-blue](https://user-images.githubusercontent.com/31796326/50386449-91e1b100-070c-11e9-9f9b-67feef27397e.png)

**Comment by gutsytechster** [comment]
![button-light-blue](https://user-images.githubusercontent.com/31796326/50386451-99a15580-070c-11e9-9efa-1349a52b68c7.png)

**Comment by gutsytechster** [comment]
Which one looks good? @monsij

**Comment by monsij** [comment]
Reacted!

**Comment by gutsytechster** [comment]
![label](https://user-images.githubusercontent.com/31796326/50402189-949adf80-07ba-11e9-94a7-a726c694b798.png)

**Comment by gutsytechster** [comment]
@monsij ^^

**Comment by monsij** [comment]
@gutsytechster : Open up a PR

**Comment by monsij** [comment]
Solved #97
